sylius_fixtures:
    suites:
        default:
            fixtures:
                promotion:
                    options:
                        custom:
                            sponsorship:
                                code: 'SPONSORSHIP'
                                name: 'Sponsorship'
                                channels:
                                    - 'FASHION_WEB'
                                coupon_based: true
