sylius_fixtures:
    suites:
        default:
            fixtures:
                promotion:
                    options:
                        custom:
                            sponsorship:
                                code: 'SPONSORSHIP'
                                name: 'Sponsorship'
                                channels:
                                    - 'FASHION_WEB'
                                coupon_based: true
                                rules:
                                    -   type: "nth_order"
                                        configuration:
                                            nth: "1"
                                actions: 
                                    -   type: order_percentage_discount
                                        configuration:
                                            percentage: 30

sylius_ui:
    events:
        sylius.shop.register.form:
            blocks:
                after_legacy:
                    template: "@AcmeSyliusSponsorshipPlugin/Register/_sponsor.html.twig"
                    priority: 1
