# imports:
#     - { resource: sylius_fixtures.yml }

parameters:
    sylius_sponsorship_plugin.promotion_code: 'SPONSORSHIP'
    sylius_sponsorship_plugin.usage_limit: 5

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        public: true


    sylius_sponsorship_plugin.user.registration_listener:
        class: Acme\SyliusSponsorshipPlugin\EventListener\UserRegistrationListener
        arguments:
            $promotionCode: '%sylius_sponsorship_plugin.promotion_code%'
            $usageLimit: '%sylius_sponsorship_plugin.usage_limit%'
        tags:
            - { name: kernel.event_listener, event: sylius.customer.post_register, method: createPromotionCoupon }

    app.form.type.customer_sponsorship_registration:
        class: Acme\SyliusSponsorshipPlugin\Form\CustomerSponsorshipRegistrationType
        arguments:
            - '%sylius.model.customer.class%'
            - '%sylius.form.type.customer_registration.validation_groups%'
            - 'sylius.repository.customer'
        tags:
            - { name: form.type }

    app.form.type.sponsor_type:
        class: Acme\SyliusSponsorshipPlugin\Form\SponsorType
        arguments:
            - '%sylius.model.shop_user.class%'
            - '%sylius.form.type.customer_registration.validation_groups%'
        tags:
            - { name: form.type }
