# imports:
#     - { resource: sylius_fixtures.yml }

parameters:
    sylius_sponsorship_plugin.promotion_code: 'SPONSORSHIP'

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        public: true


    sylius_sponsorship_plugin.user.registration_listener:
        class: Acme\SyliusSponsorshipPlugin\EventListener\UserRegistrationListener
        arguments:
            $promotionCode: '%sylius_sponsorship_plugin.promotion_code%'
        tags:
            - { name: kernel.event_listener, event: sylius.customer.post_register, method: createPromotionCoupon }
